name: Deploy client to AWS Beanstalk
# Trigger the workflow on push to main
on: 
  push:
    branches:
      - main

jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source code
        uses: actions/checkout@v3 

      - name: Login to docker
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build client image
        working-directory: ./client
        run: docker build -t jmarc101/client -f Dockerfile.dev .
      
      - run: docker run -e CI=true jmarc101/client npm run test
      
      - name: Generate client deployement package
        working-directory: ./client
        run: zip -r client-deploy.zip . -x "*.git"

      # Deploy the client to AWS Beanstalk
      # Uses the beanstalk-deploy action
      # https://github.com/einaregilsson/beanstalk-deploy
      - name: Deploy to AWS Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: docker-client
          environment_name: Docker-client-env
          version_label: 1.1.0
          region: us-east-2
          deployment_package: client/client-deploy.zip
