# Name shown in Actions tab
name: Run tests

# Controls when the action will run. Triggers the workflow on push or pull request
on: [pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a
  # single job called "test"
  test:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v3
     - name: Build and test server
       working-directory: ./client-slim
       run: docker build -t react-app -f Dockerfile.dev .
     - run: docker run -e CI=true react-app npm run test