# Name shown in Actions tab
name: Run tests

# Controls when the action will run. Triggers the workflow onweb pull request
on: [pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a
  # single job called "test"
  test:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v3
     - name: Build client-slim test image
       working-directory: ./client
       run: docker build -t jmarc101/client -f Dockerfile.dev .
     - name: Run client-slim test
       run: docker run -e CI=true jmarc101/client npm run test
